name: Deploy Go Application to EC2

on:
  push:
    branches:
      - deploy-to-ec2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Create .env file
        run: echo "PORT=${{secrets.PORT}}" >> .env

      - name: Login to Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build Docker Image
        run: docker build -t lmen776/go-app .

      - name: Push Image to Docker Hub
        run: docker push lmen776/go-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image
        run: sudo docker pull lmen776/go-app:latest

      - name: Delete Old Container
        run: docker rm -f go-app-container || true  # Prevent errors if container doesn't exist

      - name: Run Docker Containers 
        run: sudo docker run -d -p 4040:4040 --name go-app-container lmen776/go-app 
